### ISSUE TITLE
Does the Crossbell Chain use ETH  Pos

### ISSUE THREAD

**Issue by wujunze** [Crossbell-Box/crossbell.io#108]
Hello : 
Does the Crossbell Chain use ETH  Pos
Will the code be open source

**Comment by Atlasoin** [comment]
Hi, Crossbell chain is currently using ETH POA with some customized modifications, and a roadmap about the upgrade using rollup techniques is on the way. 

It's not open-sourced yet but it definitely will be in the future.

**Comment by wujunze** [comment]
Thanks @Atlasoin
